version: "3.7"

services:
  api-be:
    image: api-be
    build:
      target: api-be
      context: ./api-be
      # dockerfile: api-be/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./api-be/app:/app
      - ./api-be/dataFiles:/dataFiles
    depends_on:
      - "db"
  analysis-be:
    image: analysis-be
    build:
      target: analysis-be
      context: ./analysisBackend
      # dockerfile: analysisBackend/Dockerfile
    ports:
      - 3200:3200
    volumes:
      - ./analysisBackend:/analysisBackend
    depends_on:
      - "db"
  db:
    image: postgis/postgis:14-3.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 5433:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - "db"