version: "3.7"

services:
  app:
    image: node:18-alpine
    command: sh -c "npm install && npm run serve"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./app:/app
      - ./dataFiles:/dataFiles
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 5433:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080